### ISSUE TITLE
Azure unable to find flask_sqlalchemy library

### ISSUE THREAD

**Issue by atulverma1212** [udacity/nd081-c3-Migrating-Non-Native-Cloud-Applications-project-starter#1]
When the app is deployed on azure webapp through terminal. I am following the below tutorial by microsoft azure: https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-python?tabs=bash
The required flask_sqlalchemy library is also freezed in the requirements file
`Flask-SQLAlchemy==2.4.3`
Yet azure webapp throws error that this library is not found.
I am running webapp on linux environment with python version 3.7

**Comment by SudKul** [comment]
We recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors so that new students can learn from your discussion.
